version: '3.8'
services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    volumes:
     - dynamodb_data:/home/dynamodblocal
    ports:
      - '127.0.0.1:8000:8000'
volumes:
  dynamodb_data:
